name: Auto PR Branch Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  clean-auto-pr:
    if: ${{ github.event.pull_request.merged }} &&
        ${{ github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id }} &&
        ${{ github.event.pull_request.head.ref == 'auto-pr-*' }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/github-script@v7
          name: Delete merged auto-pr branch
          with:
            github-token: ${{ github.token }}
            script: |
                await context.github.git.deleteRef({
                  ...context.repo,
                  ref: `heads/${{github.event.pull_request.head.ref}}`,
                });
  